### ISSUE TITLE
Требуется проверка работосаособности

### ISSUE THREAD

**Issue by Elbeard** [aever32/server_trio#2]
Я программу на части поделил, перепроверь правильно ли я условия расставил, и ещё программа ругается на вызов функции send_json_to_client() в модуле проверки

**Comment by Elbeard** [comment]
Смотри! В главном файле надо создать переменную result_ver присваивать ей результат проверки (если клиент ошибся то в чём, или что всё в порядке), а переменную в главном файле передавать в функцию send_json_to_client(server_stream, result_ver ), тогда всё заработает, а то модуль проверки не знает функции send_json_to_client(). Кстати, длинну пароля и имени я подправил, как ты просил.

**Comment by aever32** [comment]
В главном файле уже есть проверка результата выполнения функции  clean_registration. 
В блоке регистрации (функция registration) есть следующий код:

```
result = await clean_registration(data)
    if result['flag'] == 'true':
       ... В этой части проводится запись в БД... 
    else:
        # отсылаем конкретную ошибку клиенту
        await send_json_to_client(server_stream, result) 
```
_Из функции clean_registration возвращается словарь с результатом проверки, если все регулярки прошли = 'true', иначе = 'причина' ошибки._
